### ISSUE TITLE
GetVersionstampRequest will fail when called before commit()

### ISSUE THREAD

**Issue by panghy** [panghy/lionrock#28]
```
    2021-07-30 12:41:02.822 DEBUG [fdb-facade,edda1d8023320501,3f0a710f037febd1] 17742 --- [ault-executor-1] i.g.p.l.f.FoundationDbGrpcFacade         : GetVersionstampRequest
    2021-07-30 12:41:02.823 DEBUG [fdb-facade,edda1d8023320501,3856634697770a7e] 17742 --- [ault-executor-1] i.g.p.l.f.FoundationDbGrpcFacade         : CommitTransactionRequest
    2021-07-30 12:41:02.826  WARN [fdb-facade,edda1d8023320501,3856634697770a7e] 17742 --- [     fdb-java-4] i.g.p.l.f.FoundationDbGrpcFacade         : failed to get versionstamp

    com.apple.foundationdb.FDBException: Transaction does not have a valid commit version
        at com.apple.foundationdb.FutureKey.FutureKey_get(Native Method) ~[fdb-java-6.3.17.jar:na]
        at com.apple.foundationdb.FutureKey.getIfDone_internal(FutureKey.java:37) ~[fdb-java-6.3.17.jar:na]
        at com.apple.foundationdb.FutureKey.getIfDone_internal(FutureKey.java:27) ~[fdb-java-6.3.17.jar:na]
        at com.apple.foundationdb.NativeFuture.marshalWhenDone(NativeFuture.java:63) ~[fdb-java-6.3.17.jar:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

**Comment by panghy** [comment]
https://github.com/apple/foundationdb/blob/904a39e4739664524dbf0df4d4d478ae7ae9e622/fdbclient/NativeAPI.actor.cpp#L4297

Hm, perhaps that's right?
